<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'blatest' => '/BlaTest.php',
                'emailtest' => '/EmailTest.php',
                'nicknametest' => '/NicknameTest.php',
                'userhelpertrait' => '/UserHelperTrait.php',
                'usertest' => '/UserTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
